USE EXCELR11;
/*WAQTD NUMBER OF EMPLOYEES WORKING IN EACH
  DEPTNO*/
  /*GROUP BY CLAUSE:
  "IT IS USED FOR GROUPING RECORDS".
  ->GROUP BY CLAUSE WILL EXCEUTE ROW_BY_ROW.
 SYNTAX:
 SELECT GROUP BY EXPRESSION/GROUP FUNCTION
 FROM TABLE_NAME
 [WHERE <FILTER CONDITION>]
 GROUP BY COLUMN_NAME/EXPRESSION;
 */
 SELECT COUNT(*),DEPTNO
 FROM EMP
 GROUP BY DEPTNO;
 /*WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPTNO
   EXCEPT ANALYST*/
 SELECT COUNT(*),DEPTNO
 FROM emp
 WHERE JOB NOT IN('ANALYST')
 GROUP BY DEPTNO;
 
 SELECT MAX(SAL),MIN(SAL),SUM(SAL),AVG(SAL),SAL*12
 FROM EMP
 GROUP BY SAL*12;
 /*WAQTD NUMBER OF EMPLOYEES WORKING IN EACH JOB*/
 SELECT COUNT(*),JOB
 FROM EMP
 GROUP BY JOB;
 /*WAQTD NUMBER OF DEPTNO PRESENT IN EMPLOYEE TABLE*/
 SELECT COUNT(DISTINCT DEPTNO)
 FROM EMP;
 /*WAQTD NUMBER OF TIMES SALARY PRESENT IN EMPLOYEE
 TABLE*/
 SELECT COUNT(*),SAL
 FROM emp
 GROUP BY SAL;
 /*WAQTD NUMBER OF TIMES JOBS PRESENT IN EMPLOYEE TABLE*/
 SELECT COUNT(*),JOB
 FROM EMP
 GROUP BY JOB;
 /*WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPTNO
 IF THERE ARE ATLEAST 3 EMPLOYEES WORKING IN EACH DEPTNO*/
 SELECT COUNT(*),DEPTNO
 FROM EMP
 GROUP BY DEPTNO
 HAVING COUNT(*)>=5;
 /*WAQTD NUMBER OF EMPLOYEES WORKING EACH DEPTNO
 EXCEPT SALESMAN IF THERE ARE ATLEAST 4 EMPLOYEES WORKING
 IN EACH DEPTNO*/
 SELECT COUNT(*),DEPTNO
 FROM emp
 WHERE JOB!='SALESMAN'
 GROUP BY DEPTNO
 HAVING COUNT(*)>=4;
 
 /*HAVING CLAUSE:
 "IT IS USED FOR FILTER THE GROUPS"
 ->HAVING CLAUSE WILL EXECUTE GROUP_BY_GROUP.
 SYNTAX:
 SELECT GROUP BY EXPRESSION/GROUP FUNCTION
 FROM TABLE_NAME
 [WHERE <FILTER CONDITION>]
 GROUP BY COLUMN_NAME/EXPRESSION
 HAVING <FILTER_GROUP_CONDITION>;
 
 /*WAQTD MAXIMUM SALARY GIVEN TO EACH JOB.IF MAXIMUM SALARY IS MORE THAN
 3500*/
 SELECT MAX(SAL),JOB
 FROM EMP
 GROUP BY JOB
 HAVING MAX(SAL)>3500;
 /*WAQTD TOTAL SALARY GIVEN TO EACH JOB IF EMPLOYEE IS GETTING SALARY
 MORE THAN 2800*/
 SELECT SUM(SAL),JOB
 FROM EMP
 WHERE SAL>2800
 GROUP BY JOB;
 /*WAQTD TOTAL SALARY GIVEN TO EACH DEPTNO IF SALARY IS MORE THAN 1500
 AND TOTAL SALARY IS GREATER THAN 3500*/
 SELECT SUM(SAL),DEPTNO
 FROM EMP
 WHERE SAL>1500
 GROUP BY DEPTNO
 having SUM(SAL)>3500;
 /*WAQTD NAMES WHICH ARE REPETED*/
 SELECT ENAME
 FROM EMP
 GROUP BY ENAME 
 HAVING COUNT(*)>1;
 /*WAQTD SALARY WHICH IS REPETED EXCATLY TWICE*/
 SELECT SAL,COUNT(*)
 FROM EMP
 GROUP BY SAL
 HAVING COUNT(*)=2;
 
 /*ORDER BY CLAUSE:
 "IT IS USED TO SORT THE GIVEN RESULT SET IN ASCENDING OR DESCENDING
 ORDER".
 ->BY DEFAULT ORDER BY CLAUSE WILL BE IN ASCENDING ORDER.
 ->ORDER BY CLAUSE WILL EXECUTE AFTER THE SELECT CLAUSE.
 */
 SELECT SAL
 FROM EMP
 ORDER BY SAL DESC;
 
 SELECT ENAME
 FROM EMP
 order by ENAME DESC;
 
 /*WAQTD SALARY OF EMPLOYEE IF EMPLOYEE IS GETTING SALARY MORE THAN 1000
  AND SORT THE SALARY IN ASCENDING ORDER*/
  SELECT SAL
  FROM EMP
  WHERE SAL>1000
  ORDER BY SAL ASC;
  /*WAQTD NUMBER EMPLOYEES WORKING AS SALESMAN IN EACH DEPTNO IF EMPLOYEE
  TOTAL SALARY MORE THAN 10000 AND SORT DEPTNO OF EMPLOYEE IN DESCENDING
  ORDER*/
  SELECT COUNT(*),DEPTNO
  FROM EMP
  WHERE JOB='SALESMAN'
  GROUP BY DEPTNO
  HAVING SUM(SAL)>10000
  ORDER BY DEPTNO DESC;