/*TYPES OF OPERATORS
1)ARITHAMTIC OPERATORS(+,-,*,/)
2)CONCATINATION OPERATOR(||)
"IT IS USED FOR JOINING TWO STRINGS TOGETHER".
SYNTAX:CONCAT('STRING','STRING');
EX:CONCAT('KARTHIK',KARTHIKA')->KARTHIKKARTHIKA
3)COMPARISION OPERATAOR(=,!=)
4)RELATIONAL OPERATOR(<,<=,>,>=)
5)LOGICAL OPERATORS(AND,OR,NOT)
"WE USE LOGICAL OPERATOR TO WRITE MULTIPLE CONDITIONS
IN WHERE CLAUSE.THE OUTPUT OF LOGICAL OPERATOR  IS
ALWAYS BOOLEAN VALUE(TRUE/FALSE).
1)AND:
"IT IS BINARY OPERATOR WHICH ACCEPTS 2 OPRENDS".
->AND OPERATORS IS USED WHENEVER BOTH OR ALL
THE CONDITION MUST BE SATISFIED".
1)WAQTD NAME &SALARY OF EMPLOYEE IF EMPLOYEE IS WORKING AS
MANAGER AND WORKING IN DEPTNO 20*/
SELECT ENAME,SAL
FROM EMP
WHERE JOB="MANAGER" AND DEPTNO=20;
/*WAQTD DETAILS OF EMPLOYEE IF EMPLOYEE WORKING AS ANALYST AND
GETTING SALARY MORE THAN 2800*/
SELECT *
FROM EMP
WHERE JOB="ANALYST" AND SAL>2800;
/*WAQTD DETAILS OF EMPLOYEE ALONG WITH ANNUAL SALARY IF 
EMPLOYEE IS GETTING ANNUALSALARY MORE THAN 15000 AND 
WORKING IN DEPTNO 10*/
SELECT *,SAL*12 AS ANNUALSAL
FROM EMP
WHERE SAL*12>15000 AND DEPTNO=10;
/*WAQTD NAME,JOB,HIREDATE OF EMPLOYEE IF EMPLOYEE IS GETTING
SALARY MORE THAN 2000 AND HIRED AFTER 1980 AND WORKING AS
CLERK AND WORKING IN DEPTNO 20*/
SELECT ENAME,JOB,HIREDATE
FROM EMP
WHERE SAL>2000 AND HIREDATE>'1980-12-31' AND JOB='CLERK' AND DEPTNO=20;
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE IS WORKING IN DEPTNO 10,20,30*/
/*OR:
"IT IS ALSO A BINARY OPERATOR WHICH ACCEPTS 2 OPRENDS.
->OR OPERATOR IS USED WHENEVER ANY ONE OF THE CONDITION MUST BE
SATISFIED.
*/
USE EXCELR;
SELECT ENAME
FROM EMP
WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30;
/*WAQTD NAME &JOB OF EMPLOYEE IF EMPLOYEE IS WORKING AS
MANAGER OR SALESMAN*/
SELECT ENAME,JOB
FROM EMP
WHERE JOB='MANAGER' OR JOB='SALESMAN';

/*WAQTD DETAILS OF EMPLOYEE IF EMPLOYEE IS GETTING SALARY OF RS
2000 OR 3000*/
SELECT *
FROM EMP
WHERE SAL=2000 OR SAL=3000;
/*WAQTD DETAILS OF EMPLOYEE IF EMPLOYEE IS WORKING AS SALESMAN
AND WORKING IN DEPTNO 20 OR DEPTNO 30 AND GETTING SALARY MORE 
THAN 1000*/
SELECT *
FROM EMP
WHERE JOB='SALESMAN' AND (DEPTNO=20 OR DEPTNO=30) AND SAL>1000;
/*WAQTD NAME,JOB ,HIREDATE OF EMPLOYEE IF EMPLOYEE IS HIRED AFTER 1981
OR WORKING AS ANALYST OR SALESMAN OR MANAGER AND WORKING IN DEPTNO
20 OR DEPTNO 30 AND GETTING SALARY MORE THAN 2000*/
SELECT ENAME,JOB,HIREDATE
FROM EMP
WHERE (HIREDATE>'1981-12-31' OR JOB='ANALYST' OR JOB='SALESMAN' OR
JOB='MANAGER') AND (DEPTNO=20 OR DEPTNO=30) AND SAL>2000;
/*WAQTD DETAILS OF EMPLOYEE ALONG WITH 40% HIKE IF EMPLOYEE IS HIRED AFTER 1980 BUT
BEFORE 1987 AND WORKING  AS SALESMAN OR PRESIDENT OR CLERK AND WORKING IN DEPTNO
10 OR 20*/
SELECT *,SAL+SAL*40/100
FROM EMP
WHERE HIREDATE>'1980-12-31' AND HIREDATE<'1987-01-01' AND 
(JOB='SALESMAN' OR JOB='PRESIDENT' OR JOB='CLERK') AND (DEPTNO=10 OR DEPTNO=20);

/*NOT:
"IT IS UNARY OPERATOR WHICH ACCEPTS SINGLE OPREND"*/
/*WAQTD NAME & DEPTNO IF EMPLOYEE IS NOT WORKING IN DEPTNO 30*/
SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO<>30;
-- WHERE NOT DEPTNO=30;
-- WHERE DEPTNO!=30;
/*WAQTD NAME &JOB OF EMPLOYEE IF EMPLOYEE IS NOT WORKING AS SALESMAN*/
SELECT ENAME,JOB
FROM EMP
WHERE JOB<>'SALESMAN';
/*SPECIAL OPERATOR:
1)IN
"IT IS MULTIVALUED OPERATOR WHICH ACCEPTS MULTIPLE VALUES AT
THE R.H.S.
SYNTAX:COLUMN_NAME/EXPRESSION IN(V1,V2,V3...VN);
*/
SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO IN(10,20,30);
-- WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30;
/*WAQTD DETAILS OF EMPLOYEE IF EMPLOYEE IS WORKING AS MANAGER
OR SALESMAN AND WORKING IN DEPTNO 20 OR 30*/
SELECT *
FROM EMP
WHERE JOB IN('SALESMAN','MANAGER') AND DEPTNO IN(20,30);
/* 2)NOT IN
"IT IS SIMILAR TO IN OPERATOR INSTEAD OF SELECTING VALUES VALUES
ARE GETTING REJECTED".
SYNTAX:COLUMN_NAME/EXPRESSION NOT IN(V1,V2,V3,.......VN);
/*WAQTD NAME &DEPTNO OF EMPLOYEE IF EMPLOYEE IS NOT WORKING IN
DEPTNO 20&30*/
SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO!=20 AND DEPTNO!=30;
-- WHERE DEPTNO NOT IN(20,30);
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE HIRED DURING 1981*/
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE>='1981-01-01' AND HIREDATE<='1981-12-31';
/*BETWEEN:
"IT IS USED TO SELECT RANGE OF VALUES".
SYNTAX:
COLUMN_NAME BETWEEN 'LOWERRANGE AND HIGHERRANGE'*/
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-12-31';
/*WAQTD NAME & SALARY OF EMPLOYEE IF EMPLOYEE IS GETTING SALARY
IN THE RANGE OF 2500 AND 1500*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL BETWEEN 1500 AND 2500;



BETWEEN
4)NOT BETWEEN
5)IS 
6)IS NOT
7)LIKE 
8)NOT LIKE*/



