use excelr;
/*Not between:
"it is opposite of between operator"
syntax:
column_name not between lowerrange and higherrange;
*/
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE IS NOT GETTING
SALARY IN THE RANGE OF 1000 AND 5000*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 5000;
/*WAQTD NAME& HIREDATE OF EMPLOYEE IF EMPLOYEE 
NOT HIRED DURING 1981*/
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE NOT BETWEEN '1981-01-01' AND
'1981-12-31';
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE IS NOT
  GETTING COMMISSION*/
/*IS:
"IT IS USED TO COMPARE WITH NULL VALUES".
SYNTAX:COLUMN_NAME/EXPRESSION IS NULL;
->CHARACTERISTICS OF NULL
1)NULL MEANS ITS EMPTY CELL OR NOTHING.
2)ZERO CANNOT BE CALLED AS NULL.
3)ALONG WITH NULL WE CANNOT PERFORM ANY ARITHAMATIC
OPERATION.IF WE PERFORM ANY ARITHAMATIC OPERATION WITH NULL
WE WILL GET RESULT AS NULL ITSELF.
4)NULL WILL NOT OCCUPY ANY MEMORY OR SPACE.
*/
SELECT ENAME,COMM
FROM EMP
WHERE COMM IS NULL;
SELECT *
FROM EMP;

SELECT SAL
FROM EMP
WHERE SAL IS NULL;
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE DOESNOT HAVE ANY
REPORTING MANAGER*/
SELECT *
FROM EMP;
UPDATE EMP
SET COMM=750
WHERE ENAME='JONES';
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE IS GETTING COMMISSION*/
SELECT ENAME,COMM
FROM EMP
WHERE COMM IS NOT NULL;


SELECT *
FROM EMP;
/*WAQTD DETAILS OF EMPLOYEE IF EMPLOYEE IS GETTING SALARY
BUT NOT COMMISSION*/
SELECT *
FROM EMP
WHERE SAL IS NOT NULL AND COMM IS NULL;
/*LIKE:
"IT IS USED FOR PATTERN MATCHING"
->TO ACHIEVE THIS PATTERN MATCHING WE REQUIRE 2 SYMBOLS
1)%
2)_
SYNTAX:COLUMN_NAME LIKE 'PATTERN_TO_MATCH';
*/
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME STARTS WITH
  A*/
  SELECT ENAME
  FROM EMP
  WHERE ENAME LIKE 'A%';
 /*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME ENDS WITH R*/
 SELECT ENAME
 FROM EMP
 WHERE ENAME LIKE '%R';
 
 /*WAQTD NAME OF EMPLOYEE IF EMPLOYEE STARTS WITH 
  M &ENDS WITH R*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'M%%R';
-- WHERE ENAME LIKE 'M%R';
-- WHERE ENAME LIKE 'M%' AND ENAME LIKE '%R';
 /*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME HAS CHARACTER
 A IN THERE NAME*/
 SELECT ENAME
 FROM EMP
 WHERE ENAME LIKE '%A%';
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAMES HAS 4 CHARACTERS*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '____';
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAMES 2ND CHARACTER
STARTS WITH L*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '_L%';
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAMES THIRD CHARACTER
STATRTS WITH R*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '__R%';
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAMES LAST BUT ONE
  CHARACTER IS E*/
  SELECT ENAME
  FROM EMP
  WHERE ENAME LIKE '%E_';
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME STARTS WITH
VOWELS(A,E,I,O,U)*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'A%' OR ENAME LIKE 'E%' OR 
ENAME LIKE 'I%' OR ENAME LIKE 'O%' OR ENAME LIKE 'U%';

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME DOES NOT START
WITH VOWELS*/
SELECT ENAME
FROM EMP
WHERE ENAME NOT LIKE 'A%' AND ENAME NOT LIKE 'E%'
AND ENAME NOT LIKE 'I%' AND ENAME NOT LIKE 'O%'
AND ENAME NOT LIKE 'U%';
/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME HAS
  _ IN THEIR NAME*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '_';
-- WHERE ENAME LIKE '%_%';
UPDATE EMP
SET ENAME='S_MITH'
WHERE SAL=800;
SELECT ENAME
FROM EMP;

SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%#_%' ESCAPE '#';
UPDATE EMP
SET ENAME='SMITH'
WHERE SAL=800;
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%@%%' ESCAPE '@';


